version: 2
jobs:

  compare_base_dockerfiles:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout:
          path: /home/circleci/nipype
      - run:
          name: Prune base Dockerfile in preparation for cache check
          working_directory: /home/circleci/nipype/docker
          command: |
            mkdir -p /tmp/docker
            # Use the sha256 sum of the pruned Dockerfile as the cache key.
            ash prune_dockerfile.sh Dockerfile.base > /tmp/docker/Dockerfile.base-pruned
      - restore_cache:
          # TODO: change this to 'master' after we are sure this works.
          key: dftest-v5-enh/circleci-neurodocker-{{ checksum "/tmp/docker/Dockerfile.base-pruned" }}

      - run:
          name: Prune base Dockerfile to update cache
          working_directory: /home/circleci/nipype/docker
          command: |
            mkdir -p /tmp/docker/cache
            # Use the sha256 sum of the pruned Dockerfile as the cache key.
            ash prune_dockerfile.sh Dockerfile.base > /tmp/docker/cache/Dockerfile.base-pruned
      - save_cache:
          paths:
            - /tmp/docker/cache/Dockerfile.base-pruned
          key: dftest-v5-{{ .Branch }}-{{ checksum "/tmp/docker/Dockerfile.base-pruned" }}

      - run:
          name: Determine how to get base image
          command: |
            if [ -f /tmp/docker/cache/Dockerfile.base-pruned ]; then
              echo "Cache found. Will pull base image."
              echo 'export GET_BASE=PULL' > /tmp/docker/get_base_image.sh
            else
              echo "Cache not found. Will build base image."
              echo 'export GET_BASE=BUILD' > /tmp/docker/get_base_image.sh
            fi
      - persist_to_workspace:
          root: /tmp
          paths:
            - docker/*


  build_and_test:
    parallelism: 4
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201710-02
    steps:
      - checkout:
          path: /home/circleci/nipype
      - attach_workspace:
          at: /tmp
      - run:
          name: Get test dependencies
          command: |
            pip install --no-cache-dir codecov
      - run:
          name: Modify Nipype version if necessary
          working_directory: /home/circleci/nipype
          command: |
            if [ "$CIRCLE_TAG" != "" ]; then
              sed -i -E "s/(__version__ = )'[A-Za-z0-9.-]+'/\1'$CIRCLE_TAG'/" nipype/info.py
            fi
      - run:
          name: Get base image (pull or build)
          no_output_timeout: 60m
          working_directory: /home/circleci/nipype
          command: |
            source /tmp/docker/get_base_image.sh
            if [ "$GET_BASE" == "PULL" ]; then
              echo "Pulling base image ..."
              docker pull kaczmarj/nipype:base
            elif [ "$GET_BASE" == "BUILD" ]; then
              echo "Building base image ..."
              docker build -t kaczmarj/nipype:base - < docker/Dockerfile.base
            else
              echo "Error: method to get base image not understood"
              exit 1
            fi
      - run:
          name: Build main image (py36)
          no_output_timeout: 60m
          working_directory: /home/circleci/nipype
          command: |
            e=1 && for i in {1..5}; do
              docker build \
                --rm=false \
                --tag kaczmarj/nipype:latest \
                --tag kaczmarj/nipype:py36 \
                --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
                --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
                --build-arg VERSION="${CIRCLE_TAG}" /home/circleci/nipype \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Build main image (py27)
          no_output_timeout: 60m
          working_directory: /home/circleci/nipype
          command: |
            e=1 && for i in {1..5}; do
              docker build \
                --rm=false \
                --tag kaczmarj/nipype:py27 \
                --build-arg PYTHON_VERSION_MAJOR=2 \
                --build-arg PYTHON_VERSION_MINOR=7 \
                --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
                --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
                --build-arg VERSION="${CIRCLE_TAG}-py27" /home/circleci/nipype \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Download test data
          no_output_timeout: 20m
          working_directory: /home/circleci/examples
          environment:
            OSF_NIPYPE_URL: "https://files.osf.io/v1/resources/nefdp/providers/osfstorage"
          command: |
            export DATA_NIPYPE_TUTORIAL_URL="${OSF_NIPYPE_URL}/57f4739cb83f6901ed94bf21"
            curl -sSL --retry 5 --connect-timeout 15 "$DATA_NIPYPE_TUTORIAL_URL" | tar xj

            export DATA_NIPYPE_FSL_COURSE="${OSF_NIPYPE_URL}/57f472cf9ad5a101f977ecfe"
            curl -sSL --retry 5 --connect-timeout 15 "$DATA_NIPYPE_FSL_COURSE" | tar xz

            export DATA_NIPYPE_FSL_FEEDS="${OSF_NIPYPE_URL}/57f473066c613b01f113e7af"
            curl -sSL --retry 5 --connect-timeout 15 "$DATA_NIPYPE_FSL_FEEDS" | tar xz
      - run:
          name: Run tests
          no_output_timeout: 4h
          environment:
            WORKDIR: /home/circleci/work
          command: |
            mkdir -p "$WORKDIR"
            chmod -R 777 "$WORKDIR"
            echo "not running tests now"
            # bash /home/circleci/nipype/.circleci/tests.sh
      - store_artifacts:
          path: /home/circleci/work/tests
      - run:
          name: Save Docker images to workspace
          no_output_timeout: 60m
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "0" ] && [ "$CIRCLE_BRANCH" == "enh/circleci-neurodocker-test"]; then
              docker save kaczmarj/nipype:base \
                          kaczmarj/nipype:latest \
                          kaczmarj/nipype:py36 \
                          kaczmarj/nipype:py27 > /tmp/docker/nipype-base-latest-py36-py27.tar
            fi
      - persist_to_workspace:
          root: /tmp
          paths:
            - docker/*


  deploy:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout:
          path: /home/circleci/nipype
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Load saved Docker images.
          no_output_timeout: 60m
          command: |
            docker load < /tmp/docker/nipype-base-latest-py36-py27.tar
      - run:
          name: Push to DockerHub
          no_output_timeout: 120m
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push kaczmarj/nipype:base
            docker push kaczmarj/nipype:latest
            docker push kaczmarj/nipype:py36
            docker push kaczmarj/nipype:py27
      - run:
          name: Prune base Dockerfile to update cache
          working_directory: /home/circleci/nipype/docker
          command: |
            mkdir -p /tmp/docker/cache
            # Use the sha256 sum of the pruned Dockerfile as the cache key.
            ash prune_dockerfile.sh Dockerfile.base > /tmp/docker/cache/Dockerfile.base-pruned
      - save_cache:
          paths:
            - /tmp/docker/cache/Dockerfile.base-pruned
          key: dftest-v5-{{ .Branch }}-{{ checksum "/tmp/docker/cache/Dockerfile.base-pruned" }}


workflows:
  version: 2
  build_test_deply:
    jobs:
      - compare_base_dockerfiles
      - build_and_test:
          requires:
            - compare_base_dockerfiles
      - deploy:
          filters:
            branches:
              # TODO: change this to master after we are sure this works.
              only: enh/circleci-neurodocker-test
          requires:
            - build_and_test
